# Generated by Django 4.2.7 on 2023-11-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_customer_email_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='full_name',
        ),
    ]
