# Generated by Django 4.2.7 on 2023-11-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_name_customer_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
    ]
